name: Build Jar File

on:
  push:
  workflow_dispatch:

jobs:
  build_jar_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Jar File
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Jar File
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: ./build/libs/
